image: openjdk:8

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

cache:
  key: $CI_PROJECT_NAME
  paths:
  - .gradle/wrapper/
  - .gradle/caches/

stages:
- build

release_build:
  stage: build
  tags:
  - streleng
  script:
  - >
    ./gradlew -PenableCrossCompilerPlugin=true -Pversion=${CI_COMMIT_TAG} build publish --stacktrace
    -PsmartThingsUserName=$ARTIFACTORY_USERNAME
    -PsmartThingsPassword=$ARTIFACTORY_PASSWORD
  only:
  - tags
